sculpin_content_types:
    projects:        
        permalink: project/:basename/
    posts:
        permalink: blog/:year/:month/:day/:filename/
        # type: path
        # path: _projects
        # permalink: pretty
        # taxonomies:
            # - tags
            # - categori es

services:
    skip_sources:
        class: SculpinTools\SkipSources
        arguments:
            # more about this below
            - ["components/*", "_posts/.git", "_posts/.gitignore"]
        tags:
            - { name: kernel.event_subscriber }